Remove redundant cpy ctor
It removes the default operator= and that is deprecated according to
gcc.

/home/runner/work/libshv/libshv/libshvchainpack/include/shv/chainpack/../../../src/chainpack/rpcmessage.h: In member function ‘shv::chainpack::RpcRequest& shv::chainpack::RpcRequest::operator=(const shv::chainpack::RpcRequest&)’:
/home/runner/work/libshv/libshv/libshvchainpack/include/shv/chainpack/../../../src/chainpack/rpcmessage.h:141:32: error: implicitly-declared ‘shv::chainpack::RpcMessage& shv::chainpack::RpcMessage::operator=(const shv::chainpack::RpcMessage&)’ is deprecated [-Werror=deprecated-copy]
  141 | class SHVCHAINPACK_DECL_EXPORT RpcRequest : public RpcMessage
      |                                ^~~~~~~~~~
/home/runner/work/libshv/libshv/libshvchainpack/include/shv/chainpack/../../../src/chainpack/rpcmessage.h:44:9: note: because ‘shv::chainpack::RpcMessage’ has user-provided ‘shv::chainpack::RpcMessage::RpcMessage(const shv::chainpack::RpcMessage&)’
   44 |         RpcMessage(const RpcMessage &val);